### ISSUE TITLE
Request for data json file (social_preference.json) for research purpose

### ISSUE THREAD

**Issue by thu-unicorn** [X-PLUG/RoleInteract#2]
I would like to request **“json_file data/social_preference.json”** from your GitHub Project for research purpose. Should you see this, please respond. I would greatly appreciate your assistance.

**Comment by chenhehong** [comment]
Thank you for your interest in our project. The benchmark data will be released soon. You can star our project so that you will be notified as soon as we release the data

**Comment by duongnghia222** [comment]
please release

**Comment by homzer** [comment]
We have released our data. And the evaluation code will be released soon.
